apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patches:
- deployment-patch.yaml
- service-patch.yaml
- ingress-patch.yaml
resources: []
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: homelab-cicd-helloworld
  path: deployment-patch-port.yaml
- target:
    version: v1
    kind: Service
    name: homelab-cicd-helloworld
  path: service-patch-port.yaml
